### ISSUE TITLE
compile error on gcc 14.2.0

### ISSUE THREAD

**Issue by mniehren** [jerily/tjson#2]
Hi,

i try to compile the module with tcl V8.6.15 with gcc 14.2.0 and got the attached errors ...

maybe you can fix that

Greetings,
  Michael
[compile-error.txt](https://github.com/user-attachments/files/17375799/compile-error.txt)

**Comment by jerily** [comment]
Hi, I will check over the weekend. Thanks for reporting.

**Comment by jerily** [comment]
pls check latest

**Comment by mniehren** [comment]
work's like a charm now, may thanks
